Clean up projectile
jeffsieu/last-man-sitting pull request #126
Opened 2020-05-10 15:47 UTC by owenl131

Clean up

2020-06-02 15:04 UTC, daniellimws requested changes

2020-06-02 15:04 UTC, daniellimws commented on Scripts/Projectile.cs
> +        Translation += origin;
What's `origin` initialized with?

2020-06-04 13:49 UTC, owenl131 commented on Scripts/Projectile.cs
> +        Translation += origin;
gg

2020-06-04 13:50 UTC, daniellimws commented on Scripts/Projectile.cs
> +        Translation += origin;
gg

2020-06-04 13:52 UTC, owenl131 commented on Scripts/Projectile.cs
> +        Translation += origin;
may I have the origin pleaze

2020-06-07 04:55 UTC, daniellimws commented
dotnet format failed

2020-06-07 04:56 UTC, daniellimws approved these changes
Ok can merge after fixing dotnet format

2020-06-07 05:22 UTC, merged