Revise Collectible flying mechanics
jeffsieu/last-man-sitting pull request #73
Opened 2020-03-08 16:39 UTC by jeffsieu

2020-03-08 17:46 UTC, daniellimws requested changes
Too fast liao leh, cannot la

2020-03-08 22:33 UTC, jeffsieu commented
true that

2020-03-09 16:22 UTC, jeffsieu commented
> Too fast liao leh, cannot la

Actually I just tested it, seemed okay.

2020-03-14 06:04 UTC, jeffsieu reviewed
nice work

2020-03-15 04:04 UTC, merged